---
title: "Social Capital and Covid-19"
author: "Carson"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    theme: cerulean
    highlight: tango
    code_folding: hide
indent: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


Titles: 

* Fighting Covid-19 Together: the Complementarity between Social Capital and Stringency in the United States

Subtitle: The Complementarity between Social Capital and Formal Public Health Rules in the United States

Abstract:

Social capital is a well-known determinant of health outcomes, and scholars are beginning to understand the role it plays in the spread of Covid-19. We develop a novel framework to analyze the conditions under which social capital influences preventative and infectious behaviors and, more importantly, the extent to which social capital bolsters formal public health rules like lockdown orders. With state-level data on daily Covid-19 cases, a measure of stringency, and various measures of social capital, we find that states with higher levels of social capital and higher levels of stringent policies see lower prevalence rates. These results are robust to the inclusion of standard controls and various specifications. 

These results suggest that individuals play an important role in the spread and prevention of infectious diseases independent of formal, governmental public health responses because individuals create and facilitate social capital. 

Furthermore, these results suggest that stringency measures alone are overestimated when social capital is ignored. 



# Social Capital and Covid-19

## 1. Introduction

In light of the on-going Covid-19 pandemic, scholars are beginning to examine the relationship between social capital and the spread and prevention of Covid-19 (Pitas and Ehmer, 2020; Wong and Kohler, 2020; Borgonovi and Andrieu, 2020; Borgonovi, Andrieu, and Subramanian, 2020; Wu, 2020; Wu et al., 2020; Bartscher et al., 2020; Durante et al., 2020).[^1] The influence social capital has on health outcomes in general is well-studied (Putnam, 2000), and there is even some recognition that social capital influences the spread of infectious diseases by encouraging the use of vaccinations (Nawa and Fujiwara, 2014; Palanisamy, Gopichandran, and Kosalram, 2018) and other behaviors related to influenza (Ronnerstrand, 2013 and 2014; Chuang et al., 2015).

[^1]: Putnam (2000: 19) defines social capital as the "connections among individuals---social networks and the norms of reciprocity and trustworthiness that arise from them."

While the emerging literature on social capital and Covid-19 generally shows that social capital encourages preventative behavior, few recognize the conditions under which social capital encourages preventative behavior and complements preventative policies. It is plausible that people with stronger social capital networks might have more interactions with each other, which could encourage infectious behavior. It is also plausible that greater social capital encourages preventative behavior via private, communal, and governmental efforts to prevent infection, as well as the adoption and enforcement of formal and informal public health rules. Existing evidence suggests that people living in counties (in the United States) with more social capital reduced their mobility at a quicker rate than people in counties with less social capital (Borgonovi and Andrieu (2020; also, see Borgonovi, Andrieu, and Subramanian, 2020).[^2] There is also suggestive evidence that people in areas with more social capital are more likely to follow formal public health rules, e.g., wearing face masks (Wu, 2020) and are more likely to have higher rates of testing (Wu et al., 2020).[^3] However, without an understanding of the conditions under which social capital is or is not effective, the efficacy of social capital and formal public health rules tend to be overestimated, which can lead to poor public health policy.

[^2]: Borgonovi, Andrieu, and Subramanian (2020) show that infection rates were initially higher in counties with more social capital, but transmission and mortality rates declined as people learned more about Covid-19. Similarly, Bartscher et al. (2020) suggests that the number of Covid-19 cases across Europe was initially higher in countries with higher social capital, but that cases increased at a slower rate in countries with higher social capital.

[^3]: Income also influences the effectiveness of lockdown orders, i.e., whether people are likely to comply with such orders (Wright et al., 2020).

Our study develops a novel framework to 1) assess the conditions under which social capital influences the spread of Covid-19 and 2) compare the effects social capital has on the growth of Covid-19 relative to more formal public health measures. We suggest that social capital has a stronger negative effect on Covid-19 growth rates as social capital strengthens and as people care more about Covid-19 prevention. [[[Restate the ambiguity: social capital by itself might have an independent positive or negative effect but together with public health policy, social capital supports stringency measures.]]] With state-level data on Covid-19 cases, social capital, and stringency---a measure of the severity of public health measures and the degree to which people within a state value Covid-19 prevention---we develop a panel model to assess these relative effects.[^4]

[^4]: Stringency serves a dual role in our framework. First, it helps us measure the normative values people have regarding Covid-19 prevention; states with higher measures of stringency are states where people have higher values of Covid-19 prevention. Obviously this is not completely accurate, but it is a relevant proxy. For example, Adolph et al. (2020) and Baccini and Brodeur (2020) show that the political affiliation of a state and its governor influences the kind and timing of stringency measures. Relatedly, McCannon (2020) argues that economic freedom influences the extent to which states adopt stringency measures. That is, states that have less economic freedom were more likely to adopt stringency measures sooner. These results suggest that stringency measures align with general values people within a state have towards Covid-19 prevention relative to other goals, e.g., economic activity. Second, stringency is an objective measure of the effect formal public health rules might have on the spread of Covid-19.

Our main result is that states with stronger social capital *and* with a higher value for Covid-19 prevention have lower rates of Covid-19 case growth than states with weaker social capital *and* with a lower value for Covid-19 prevention.This result is robust to the inclusion of control variables, instrumental variables, and alternative measures of social capital.

These results suggest that social capital plays an identifiable role in how people spread infectious diseases, which should be recognized in subsequent research in economics and public health. Furthermore, whereas Bartscher et al. (2020) suggests social capital becomes less important once lockdown orders are issued, our results suggest that social capital plays a consistently complementary role with more formal rules regarding Covid-19, from March 1, 2020 to November 1, 2020---especially when we focus on three-month periods. We also find that social capital becomes more important than stringency measures, given states can only be so stringent.

In addition to the emerging economic literature on Covid-19 and the relationship between social capital and Covid-19, this study also has implications for the larger economic literature on institutions and the extent to which formal and informal rules influence behavior. While many economists understand the role institutions have in creating incentives to engage in commercial activity (North, 1990; Baumol, 1990; Ostrom, 2005; Boettke and Coyne, 2003; Heller, 2009; Williamson, 2009; Williamson, 2011; Williamson and Kerekes, 2011; Storr, 2013; Vachris and Isaacs, 2017), the effects those institutions have on infectious and preventative behaviors---and prevalence rates---are less clear.[^5]

[^5]: While the *disease versus institutions* debate analyzes some of these issues, the focus is on teasing out the relationships between of economic and political institutions, infectious diseases, and economic development, not the determinants of infectious diseases (Bloom and Sachs, 1998; Gallup and Sachs, 2001; Acemoglu, Johnson, and Robinson, 2003; Acemoglu and Johnson, 2007 and 2014; Bloom, Canning, and Fink, 2014; Bhattacharya, 2008).

There is some recognition that when incentives encourage individuals to provide public health related goods and services, they tend to provide those services. For example, coal mining companies provided sanitation services on par with municipalities (Fishback, 1993); groups of workers provided industrial-sickness funds that were effective means of insurance (Murray, 2007); private water companies lowered mortality rates in Argentina (Galiani et al., 2005); textile mills and railroad companies provided mosquito control services prior to significant public health measures (Carson, 2016). Individuals can also alter the incentives and rules they face to provide mosquito-control (Carson, 2020), and to encourage Covid-19 prevention (Carson, forthcoming). Relatedly, people are better able to avoid infectious diseases and/or lessen mortality rates when they live in areas with greater economic freedom (Geloso and Pavlik, 2020; Candela and Geloso, 2020). The importance of social capital---and how social capital influences disease prevention---provides a complementary approach to these studies, especially as economic freedom is a driver of social capital (Berggren and Jordahl, 2006).

Informal rules or social norms also influence behavior via social capital, e.g., pro-environmental behaviors (Farrow et al., 2017) (see, Brennan et al., 2013; and Bichierri, 2017, for general treatments on social norms). Yet, few recognize the extent to which social norms influence behaviors related to the spread of infectious diseases (see, Carson, 2018, for one attempt regarding HIV in the United States). The present study provides additional insight into how social capital influences disease-related behaviors and the effectiveness of public health policy.

The importance of social capital for disease prevention---relative to other kinds of institutions and on its own---remains debatable. In the 18th and 19th centuries, for instance, formal economic and political institutions like the American Constitution and the federal structure of government made it more difficult to develop public health bureaus---to provide filtered water and respond to disease outbreaks---especially at the state and federal levels of government. Such institutional constraints protected private property, they fostered entrepreneurial activity, and led to economic development, but they delayed efforts to eliminate infectious diseases like smallpox, cholera, and yellow fever (Troesken, 2015) and diseases that spread primarily within animal and livestock populations (Olmstead and Rhode, 2015). Thus, social capital might be less effective relative to legal systems and formal bureaucracies of public health that can wield policing power. Similar to Bhattacharya's (2008) point that both institutions and diseases influence economic development---but at different times---there might be different times in history where social capital is more important relative to formal institutions of public health and *vice versa*. We demonstrate that social capital enhances public health measures. While there were relatively strong norms regarding individualism in the United States---which suggests greater social capital (Beilmann et al., 2018) and a lower willingness to regulate economic activity (Williamson, 2009; Williamson, 2013; Davis and Williamson, 2016; Cline and Williamson, 2019)---individuals did eventually create more permanent and effective public health bureaus.

Furthermore, Troesken (2015: 15-18) describes and critiques *the ideology of the township*, which suggests that tight-knit communities, e.g., American towns during the late 18th and early 19th centuries, were places where people could easily communicate with their neighbors and---if a public health issue arose---appeal to their neighbor's sense of community to encourage proper health practices.[^6] However, Troesken argues this kind of social capital is not robust in larger societies.[^7] Our framework suggests otherwise and allows us to investigate the complementarity between social capital and formal public health rules.

[^6]: Troesken focuses on Smallpox, which suggests the appropriate public health practice was inoculation or variolation.

[^7]: Tullock (1969) levies a similar critique against the use of *social pressure* as a means to resolve collective action problems in the context of mosquito control.

A related theme in the economics of institutions literature is that the formal rules that facilitate economic development depend on supporting informal rules. The implication is that mimicking formal rules without the underlying cultural values and informal rules (or *metis* following Boettke, Coyne, and Leeson, 2008) is not appropriate and likely to evince worse outcomes. Evidence on the efficacy of matching formal and informal institutions suggests that areas with higher levels of trust, self-reliance, and civic belief foster economic and political institutions that protect property rights, promote openness, and economic development (Vachris and Isaacs, 2017). Furthermore, government-led attempts to foster social capital or create homogeneity---for example, through language laws or the creation of a civil court---create unintended, harmful effects (Carilli, Coyne, and Leeson, 2008).

Thus, we resist attempts to alter the level and/or kind of social capital via policy so as to influence Covid-19 transmission rates. Social capital is not easily alterable as if it were a lever one person or a large group of people could toggle. Even though social capital supports formal public health rules and can lower the growth rate of Covid-19 cases, this does not necessarily suggest policymakers should target areas with less social capital by increasing stringency measures or double-down along the intensive margin (as suggested by Bartscher et al., 2020). Even though areas with less social capital will not experience the complementary effect social capital has on stringency, those areas might have fewer interactions in the first place which might leave them with fewer Covid-19 cases.

In any event, the relationships between social capital, formal public health rules, and the spread of infectious diseases enhances our understanding of how people spread infectious diseases. Just as we recognize individuals can influence the formal and informal rules that influence economic, political, and social behaviors, we should recognize individuals also influence how diseases spread by the formal and informal rules they create and adapt.

## 2. Social Capital, Formal Rules, and Covid-19

Social capital takes various forms between individuals so as to encourage cooperation, which then influences health outcomes. Two of the main forms of social capital include *bridging* between people within a social network and *bonding* between people from different social networks. We do not take a stance as to which form of social capital is more or less relevant in the context Covid-19. We do, however, provide evidence below regarding the measured components of social capital. Furthermore, while social capital can be used for legitimate and nefarious activities, we are solely interested in whether social capital influences disease prevalence and public policy effectiveness.

Social capital can influence health outcomes in multiple ways (Putnam, 2000; Kawachi, Subramanian, and Kim, 2008): people with greater access to social capital or in a network with stronger social capital might have more tangible assistance from others, e.g., money or health care; they might have more access to organizations that lower the cost of health care; they might have more opportunities to innovate and provide goods and services related to health; they might be in a social network where social norms enforce healthy behaviors, e.g., don't take the last bite of food; they might also have more of an ability to advance a political agenda to alter health policy; and there might be a physiological response because of social capital that improves immune systems (Putnam, 2000). Additional evidence also shows that social capital influences obesity (Kim, Subramaniam, Gortmaker, and Kawachi, 2006).

Our argument about the effect social capital has on Covid-19 prevalence rates is conditional; that is, there are conditions under which social capital encourages preventative behavior and there are conditions under which social capital encourages infectious behavior.

First, the effectiveness of social capital---as a means of limiting the spread of Covid-19 depends on the normative beliefs and attitudes people have about Covid-19 and the value of disease prevention. This follows the general understanding that social capital encourages legitimate and nefarious activities, depending on people's goals. If people know how Covid-19 spreads and they value its prevention, whatever social capital they might have can be an effective means of prevention. However, some groups might legitimately value other goals more than prevention, e.g., maintaining cultural practices, following religious observances, pursuing economic activity, etc. Thus, merely having social capital does not necessarily encourage preventative behavior.

Second, the effectiveness of social capital also depends on the extent, quality, kind, or strength of social capital people have. The kinds (and amount) of bonds people form vary in different school groups, business environments, and familial and social interactions; this is why some refer to social capital as having an entrepreneurial quality (Chamlee-Wright, 2007; Carilli, Coyne, and Leeson (2008). All else equal, we expect groups with stronger social capital to engage in more communal activity that encourages the spread of diseases.

Finally, we expect an interaction between the desires people have regarding prevention and their level of social capital. If we can separate groups into those with *strong* and *weak* social capital, for example, we expect the group with stronger social capital to have a larger effect on preventative (infectious) behavior, given they have normative beliefs that (do not) value prevention.

Table 1 depicts a way to visualize these conditions. The rows characterize groups by their normative beliefs and attitudes; groups in the top row value prevention while groups in the bottom row do not. The columns characterize groups by the strength of their social capital; groups on the left have stronger social capital while those on the right have weaker social capital.

+----------------------------+---------------------------------------------------+--------------------------------------------------+
|                            | Strong Social Capital                             | Weak Social Capital                              |
+============================+===================================================+==================================================+
| Prevention is valuable     | I - Social capital lowers prevalence rates by a   | II - Social capital lowers prevalence rates by b |
+----------------------------+---------------------------------------------------+--------------------------------------------------+
| Prevention is not valuable | III - Social capital raises prevalence rates by a | IV - Social capital raises prevalence rates by b |
+----------------------------+---------------------------------------------------+--------------------------------------------------+

: Table 1. A Framework of Social Capital and Disease Prevention

Thus, the effect social capital might have on Covid-19 prevalence rates varies by quadrant. For any given level of social capital, states with a higher desire for prevention (Quadrants I and II) should see lower prevalence rates relative to states with a lower desire for prevention (Quadrants III and IV). For a given desire of prevention, states with higher social capital (Quadrants I and III) should have higher prevalence rates than states with lower social capital (Quadrants II and IV).

In particular, we expect the magnitude of social capital to have the largest, negative effect on Covid-19 prevalence rates when people 1) value preventative behavior and 2) have stronger social capital (Quadrant I). We expect the magnitude of social capital to have the largest, positive effect on new Covid-19 cases when people 1) do not value preventative behavior and 2) have stronger social capital (Quadrant III). Whether people value prevention or not, the effect social capital has on prevalence rates will decline the weaker social capital becomes (Quadrants II and IV).

This framework is somewhat easy to operationalize. The columns can be measured with various indices of social capital, e.g., the Joint Economic Committee's (JEC) social capital project. The JEC index allows for a distinction between states with *higher* social capital and states with *lower* social capital. The rows can be measured with a measure of stringency, which we suggest is indicative of the values people hold in a state. While not perfect, it suggests that people in areas with higher stringency have place a higher value on preventing the spread of Covid-19.[^8]

[^8]: We did consider the political affiliation of state governors, but we found this was not significant.

The following testable propositions guide our analysis below:

1.  People that value Covid-19 prevention will have larger, negative effects on the growth of Covid-19 cases than people that do not value Covid-19 prevention, all else equal.

2.  The magnitudes of the prevalence rate of people with stronger social capital---regardless of whether they value Covid-19 prevention---will be larger than people with weaker social capital.

3.  People that value Covid-19 prevention *and* have stronger social capital will have the largest, negative effect on the growth of Covid-19 cases, all else equal.

Given normative beliefs and attitudes that value prevention, we posit social capital has a negative effect on prevalence rates because social capital raises the private costs to individuals of breaking the rules that a group perceives as legitimate, namely formal and informal public health rules. Municipal face mask ordinances and state-wide lockdown orders are examples of the former kind of public health rules, while wearing a face mask whilst in any public setting and covering ones' mouth for a sneeze are examples of the latter kind.[^9] While informal rules are difficult to systematically measure in large groups, we focus on the relationship between formal rules and social capital below.[^10]

[^9]: Whereas formal rules specify a primary directive and secondary qualifiers, a centralized enforcement mechanism, and it is a rule derived from some kind of governing body, informal rules might only specify a primary directive with few secondary qualifiers, enforcement is decentralized, and it is a rule derived from the normative attitudes of the individuals to which the rule applies (Brennan et al., 2013).

[^10]: See Carson (forthcoming) on the relevance of rules to encourage preventative behavior in the context of Covid-19.

Social capital encourages rule-following behavior---again assuming people have beliefs and normative attitudes that value preventative behavior---because it raises the private cost to individuals of breaking rules. Given many people believe public health rules are legitimate and valuable, breaking those rules is taken as an affront punishable informally by a personal rebuke, a worsening reputation, a refusal of service, or fewer social contacts. More formal measures of enforcement and punishment are also relevant, e.g., calling a public health department, a security guard, or the police. Relatedly, people are better able to monitor the behavior of others in areas with stronger social capital given the numerous social ties; this suggests that infractions are more likely to be discovered in areas with stronger social capital. Thus, as strong or severe as a formal public health rule is, social capital will encourage individuals to follow it. All else equal, this effect lowers the number of Covid-19 cases.

## 3. Data and Model

In order to operationalize our basic framework, we specify a simple regression equation,

*Insert equation 1,*

where the number of daily Covid-19 cases is a function of the 14-day lag of the stringency index from Oxford University's Covid-19 Government Response Tracker (OxCGRT) for the United States. We then add the square of the 14-day lag of the stringency index to demonstrate the diminishing impact of case prevalence as stringency increases. Finally, in our initial empirical treatment we interact the 14-day lagged stringency index with a dummy variable where 1 represents states with an above average value of the Joint Economic Committee's state-level social capital index. We use this dummy variable to represent a general level of social capital within a state. This simple regression equation allows us to investigate the differences in our theoretical framework between the desire for preventative measures and the level of social capital. In other words, we are able to test two of our three hypotheses: do states that desire prevention get better prevalence outcomes and does a higher rate of social capital along with more preventative measures lead to an even larger reduction in prevalence?

The data for our empirical analysis comes from a number of sources. Our dependent variable, the daily number of new cases comes from the Johns Hopkins University Covid-19 surveillance dashboard. Our stringency measures come from Oxford University's COVID-19 Government Response Tracker (OxCGRT) for the United States. This state level data provides a systematic way to measure and compare state governments' responses to the pandemic. The social capital measures and number of other demographic measures were taken from the US Congress Joint Economic Committee's Social Capital Project. This project provides us with a state-level social capital index, which uses a set of specific measures in categories such as family unity, family interaction, social support, community health, institutional health, collective efficacy, and philanthropic health. The aggregate measure is then calculated as a deviation from the mean score with a normalized mean of 0.

Our regression model for equation 1 uses a balanced panel of daily data from March 1, 2020 to November 21, 2020 across all 50 states and the District of Columbia. We estimate equation 1 using a within model that includes both cross-sectional and period fixed effects.

*Insert Table 1 here*

The first column in Table 1 provides the empirical results of equation 1. The results state that a one unit increase in the level of daily stringency reduces new cases by 10.00 per million. The effectiveness of stringency diminishes as stringency increases at a rate of 0.07 cases per million. More importantly, states with a higher than average level of social capital and a higher level of daily stringency have increased reductions in new cases by .67 per million. This multiplicative impact suggests that states with higher levels of social capital respond more "collectively," slowing daily disease spread at a higher rate than those states with lower levels of social capital, but with similar levels of stringency. These results support propositions 1 and 2.

Equation 1 is incredibly simple, so we specify a slightly more complex equation:

*insert equation 2 here,*

Equation 2 expands our analysis to include a stand-alone variable for the level of social capital, again measured using a dummy variable that equals one for a state that has an above average social capital index. This specification---presented in column 2 of Table 1---is more flexible than our equation 1 as it includes control variables. This specification also expands the initial results by analyzing state-specific controls on the impact of social capital on disease spread and the benefits of policy stringency.

Column 3 of Table 1 presents the results of equation 3, which adds a number of controls, including: median household income, the percent of adults with a bachelor's degree, the percent of a state population in fair or poor health, the percent of the population that is black, population density, the percent of the population that is rural, the percent of the population over the age of 65, and average state temperature.

*Insert Equation 3 here*

These variables are used to control for factors that could possibly influence prevalence, as well as a state's desire for prevention. Equation 3 also includes a measure for the political affiliation of the governor, where a 1 represents a Republican governor. We include this measure as an additional proxy for the desire of citizens of a state for prevention measures. We expect that Republican Governors would be less likely to implement highly stringent measures give other values. Our choice of a variable for the Governor's political party references the fact that most preventative measures have been enacted by executive order and not by legislative action. These measures were taken from the US Census American Community Survey (2019), the Bureau of Economic Analysis, and the Bureau of Labor Statistics. Data on the political party of the Governor was taken from ballotpedia.org (accessed Nov. 12, 2020).

Given that the social capital data as well as a number of our controls are state-specific and time-invariant, equations 2 and 3 use a pooled specification with period fixed effects to analyze the importance of underlying social capital differences.

The results in Columns 2 and 3 are similar to the two-way fixed effects model in Column 1 and allows us to see with greater detail some of the cross-sectional difference that have played a role in state policy stringency's impact on COVID-19 spread. In particular, stringency is still statistically significant and negative, supporting proposition 1, that people who value prevention will see lower prevalence on average. The positive and significant coefficient on the social capital dummy variable supports proposition 2 that stronger social capital will lead to higher prevalence, supporting the notion that social capital can reinforce beliefs that are counter to the prevention of disease spread {Citation?}. Finally, the negative value on the interaction term supports proposition 3, that states with higher levels of stringency and higher rates of social capital will have an even larger reduction in new cases. Other controls, like race, poverty and education level also have impacts that support previous research {Townsend et al., 2020; Yancy, 2020; }. Interestingly, the dummy representing Republican Governor is statistically insignificant.

In Table 2 we re-estimate our equations 2 and 3 with alternate measures of social capital from previous literature. These measures include: SCP version of Penn State Index (2014), the Putnam Index (2000), and the Alesina & La Ferrara social capital group (2000). All of these measures were taken from the JEC Social Capital Project dataset. Once again, our results are consistent across different measures of social capital.

*[Insert table 2 here]*

*[Insert Table 5 here]*

Table 5 reports the results of our variables of interest for equation 3.^[We did run this regression with the same controls as above, but we do not report these results; they are available upon request.] In the first half of the COVID-19 outbreak we see that increased levels of stringency had no significant effect on prevalence, though a higher level of social capital led to a statistically significant increase in prevalence. This result supports earlier findings. Our results also reiterate that states with high social capital saw a significantly lower number of cases as stringency increased. In the second half of the Covid-19 outbreak, post-July 4, we see that higher levels of stringency significantly reduce the number of daily cases, but the impact of higher stringency diminishes more rapidly. This suggests that the higher levels of initial stringency are impactful, but higher levels of stringency over a certain level are less so. Having an above average level of social capital leads to an increase of almost 415 cases per million, supporting the idea that higher social capital states, ceteris paribus, might find it difficult to maintain social distancing over time and are more susceptible to “COVID fatigue.” That said there is still a significant reduction in cases in states that have above average social capital and increased preventative measures.

## 5. Conclusion

Notes:

-   Social capital consistently influences infectious and preventative behaviors.

-   Informal rules like those found in social capital influence behavior and bolster formal rules.

-   Policy implications are difficult to tease out given social capital is emergent. Social capital is a deeper notion than merely doing what an elected official tells us to do. Trusted advisers, business contacts, friends, and family comprise our social networks and capital.

While we can easily identify measures of social capital, e.g., the number of community centers or the percent of people who donate to charitable organizations, cultivating social capital---in the way it is meant in the literature---is not so simple. Perhaps for future outbreaks, we can discuss the role social capital might have and how to bolster that capital, but it seems unlikely that it will come from a centralized source.

-   Future research should study the extent to which social capital erodes over time particularly because of formal rules that prevent interactions. That is, while we find social capital bolsters formal rules, those formal rules might extinguish the necessary parts of social capital given a longer duration or additional severity. This is especially once we recognize the cultural context within which social capital emerges, i.e., human interactions and the norms of proper behavior that develop. Formal rules that make such interactions more costly are likely to alter the costs and benefits people face such that existing social capital erodes (Carilli, Coyne, and Leeson, 2008) and alternative kinds of social capital will arise. Indeed, if formal rules prevent interactions that would have otherwise taken place, individuals realize less of a benefit from maintaining existing social ties.

Alternatively, emphasis should be placed on providing quality information about Covid-19 transmission, as well as encouraging individuals to seek out relevant tests. Such measures encourage individuals to make decisions and *invest* in existing social ties according to their values.

-   If two states have a stringency index of "6" - do they have the same policies? What are the potential differences? Same with social capital...

-   Supporting Evidence:

    -   Within states that have the worst social capital, are there pockets that have high social capital?

    \*Similarly, among the states that have really high social capital, are there pockets of really low social capital?

At the aggregate level, state scores might have social capital scores that obviously do not accurately reflect differences in social capital at the county level.

# References
